feat(Puppeteer/PlaywrightScraper): add support for headful crawling
apify/apify-sdk-js pull request #169
Opened 2023-02-06 16:50 UTC by vladfrangu

Handles a long lasting request. I would love if you had any better descriptions for the option, as I don't fully know how to describe it past...just linking to an article explaining it

2023-02-06 16:53 UTC, metalwarrior665 requested changes
Just a small nitpick

2023-02-06 16:53 UTC, metalwarrior665 commented on packages/actor-scraper/playwright-scraper/INPUT_SCHEMA.json
> +            "description": "By default, browsers run in headless mode. You can toggle this on to run them in headful mode.",
I would just add a sentence as `Headful mode can help with certain rare anti-scraping protections but is slower and more costly.`

2023-02-06 17:01 UTC, AndreyBykov commented
I would maybe instead of naming it `headful` and disabling by default name it `headless` and enable it by default, as term `headful` is rather niche. It's used more now, but from my experience it's usually `headless` or `full` in discussions/docs, and e.g. playwright does not have `headful` in docs at all. But that's rather a nit.

2023-02-06 17:02 UTC, vladfrangu commented
That makes more sense, you're right. I'll apply it :D

2023-02-06 17:03 UTC, AndreyBykov commented
@vladfrangu let's see what others think - as we use it internally from the beginning of time =D

2023-02-06 17:05 UTC, vladfrangu commented
> @vladfrangu let's see what others think - as we use it internally from the beginning of time =D

Welp, already pushed a commit 😆 If others agree with keeping it headless then yay, if not, just undo one commit and we're done :D

2023-02-06 17:32 UTC, metalwarrior665 commented
I would vote slightly more for headful as it is the thing you opt-in (and you don't have to think in double-negation) but not a big deal :)

2023-02-06 17:34 UTC, B4nan approved these changes

2023-02-06 17:36 UTC, vladfrangu commented
Maybe we can make a poll or something internally about this? What do you think?

2023-02-06 17:41 UTC, metalwarrior665 commented
@vladfrangu It is not that important I think :) Just go with your gut :)

2023-02-24 07:55 UTC, vladfrangu commented
I'm going to be merging this as is later today - to me it feels more accurate to name the option what it is (headless), defaulted to true, and it is also how users reading playwright/puppeteer docs would see it, but if you disagree let me know :D

2023-02-27 23:54 UTC, merged